// FETCH CANDIDATE
export const FETCH_CANDIDATE_LIST = 'FETCH_CANDIDATE_LIST';
export const FETCH_CANDIDATE_LIST_SUCCESS = 'FETCH_CANDIDATE_LIST_SUCCESS';
export const FETCH_CANDIDATE_LIST_ERROR = 'FETCH_CANDIDATE_LIST_ERROR';
// ADD CANDIDATE
export const ADD_CANDIDATE = 'ADD_CANDIDATE';
export const ADD_CANDIDATE_SUCCESS = 'ADD_CANDIDATE_SUCCESS';
export const ADD_CANDIDATE_ERROR = 'ADD_CANDIDATE_ERROR';
// UPDATE CANDIDATE
export const UPDATE_CANDIDATE = 'UPDATE_CANDIDATE';
export const UPDATE_CANDIDATE_SUCCESS = 'UPDATE_CANDIDATE_SUCCESS';
export const UPDATE_CANDIDATE_ERROR = 'UPDATE_CANDIDATE_ERROR';
// ADD CANDIDATE
export const REMOVE_CANDIDATE = 'REMOVE_CANDIDATE';
export const REMOVE_CANDIDATE_SUCCESS = 'REMOVE_CANDIDATE_SUCCESS';
export const REMOVE_CANDIDATE_ERROR = 'REMOVE_CANDIDATE_ERROR';
