// FETCH DEAL
export const FETCH_HELLOWORLDS_LIST = 'FETCH_DEAL_LIST';
export const FETCH_HELLOWORLDS_LIST_SUCCESS = 'FETCH_DEAL_LIST_SUCCESS';
export const FETCH_HELLOWORLDS_LIST_ERROR = 'FETCH_DEAL_LIST_ERROR';
// ADD DEAL
export const ADD_HELLOWORLD = 'ADD_HELLOWORLD';
export const ADD_HELLOWORLD_SUCCESS = 'ADD_HELLOWORLD_SUCCESS';
export const ADD_HELLOWORLD_ERROR = 'ADD_HELLOWORLD_ERROR';
// UPDATE DEAL
export const UPDATE_HELLOWORLD = 'UPDATE_HELLOWORLD';
export const UPDATE_HELLOWORLD_SUCCESS = 'UPDATE_HELLOWORLD_SUCCESS';
export const UPDATE_HELLOWORLD_ERROR = 'UPDATE_HELLOWORLD_ERROR';
// ADD DEAL
export const REMOVE_HELLOWORLD = 'REMOVE_HELLOWORLD';
export const REMOVE_HELLOWORLD_SUCCESS = 'REMOVE_HELLOWORLD_SUCCESS';
export const REMOVE_HELLOWORLD_ERROR = 'REMOVE_HELLOWORLD_ERROR';
