// FETCH LOCATIONS
export const FETCH_SPOKEN_LANGUAGE_LIST = 'FETCH_SPOKEN_LANGUAGE_LIST';
export const FETCH_SPOKEN_LANGUAGE_LIST_SUCCESS = 'FETCH_SPOKEN_LANGUAGE_LIST_SUCCESS';
export const FETCH_SPOKEN_LANGUAGE_LIST_ERROR = 'FETCH_SPOKEN_LANGUAGE_LIST_ERROR';
