// FETCH APPLICATION MODULE LIST
export const FETCH_APPLICATION_MODULE_LIST = 'FETCH_APPLICATION_MODULE_LIST';
export const FETCH_APPLICATION_MODULE_LIST_SUCCESS = 'FETCH_APPLICATION_MODULE_LIST_SUCCESS';
export const FETCH_APPLICATION_MODULE_LIST_ERROR = 'FETCH_APPLICATION_MODULE_LIST_ERROR';
// ADD APPLICATION MODULE
export const ADD_APPLICATION_MODULE = 'ADD_APPLICATION_MODULE';
export const ADD_APPLICATION_MODULE_SUCCESS = 'ADD_APPLICATION_MODULE_SUCCESS';
export const ADD_APPLICATION_MODULE_ERROR = 'ADD_APPLICATION_MODULE_ERROR';
// UPDATE APPLICATION MODULE
export const UPDATE_APPLICATION_MODULE = 'UPDATE_APPLICATION_MODULE';
export const UPDATE_APPLICATION_MODULE_SUCCESS = 'UPDATE_APPLICATION_MODULE_SUCCESS';
export const UPDATE_APPLICATION_MODULE_ERROR = 'UPDATE_APPLICATION_MODULE_ERROR';
// REMOVE APPLICATION MODULE
export const REMOVE_APPLICATION_MODULE = 'REMOVE_APPLICATION_MODULE';
export const REMOVE_APPLICATION_MODULE_SUCCESS = 'REMOVE_APPLICATION_MODULE_SUCCESS';
export const REMOVE_APPLICATION_MODULE_ERROR = 'REMOVE_APPLICATION_MODULE_ERROR';