// FETCH ROLE LIST
export const FETCH_ADMIN_ROLE_LIST = 'FETCH_ADMIN_ROLE_LIST';
export const FETCH_ADMIN_ROLE_LIST_SUCCESS = 'FETCH_ADMIN_ROLE_LIST_SUCCESS';
export const FETCH_ADMIN_ROLE_LIST_ERROR = 'FETCH_ADMIN_ROLE_LIST_ERROR';

// FETCH ADMIN ROLE DETAILS
export const FETCH_ADMIN_ROLE_DETAILS = 'FETCH_ADMIN_ROLE_DETAILS';
export const FETCH_ADMIN_ROLE_DETAILS_SUCCESS =
  'FETCH_ADMIN_ROLE_DETAILS_SUCCESS';
export const FETCH_ADMIN_ROLE_DETAILS_ERROR = 'FETCH_ADMIN_ROLE_DETAILS_ERROR';

// FETCH ROLE LIST
export const ADD_ADMIN_ROLE = 'ADD_ADMIN_ROLE';
export const ADD_ADMIN_ROLE_SUCCESS = 'ADD_ADMIN_ROLE_SUCCESS';
export const ADD_ADMIN_ROLE_ERROR = 'ADD_ADMIN_ROLE_ERROR';

// REMOVE ROLE LIST
export const REMOVE_ADMIN_ROLE = 'REMOVE_ADMIN_ROLE';
export const REMOVE_ADMIN_ROLE_SUCCESS = 'REMOVE_ADMIN_ROLE_SUCCESS';
export const REMOVE_ADMIN_ROLE_ERROR = 'REMOVE_ADMIN_ROLE_ERROR';

// ADD APPLICATION MODULE TO ROLE
export const ADD_APPLICATION_MODULE_TO_ROLE = 'ADD_APPLICATION_MODULE_TO_ROLE';
export const ADD_APPLICATION_MODULE_TO_ROLE_SUCCESS =
  'ADD_APPLICATION_MODULE_TO_ROLE_SUCCESS';
export const ADD_APPLICATION_MODULE_TO_ROLE_ERROR =
  'ADD_APPLICATION_MODULE_TO_ROLE_ERROR';
