// FETCH REQUISITION
export const FETCH_REQUISITION_LIST = 'FETCH_REQUISITION_LIST';
export const FETCH_REQUISITION_LIST_SUCCESS = 'FETCH_REQUISITION_LIST_SUCCESS';
export const FETCH_REQUISITION_LIST_ERROR = 'FETCH_REQUISITION_LIST_ERROR';
// ADD REQUISITION
export const ADD_REQUISITION = 'ADD_REQUISITION';
export const ADD_REQUISITION_SUCCESS = 'ADD_REQUISITION_SUCCESS';
export const ADD_REQUISITION_ERROR = 'ADD_REQUISITION_ERROR';
// UPDATE REQUISITION
export const UPDATE_REQUISITION = 'UPDATE_REQUISITION';
export const UPDATE_REQUISITION_SUCCESS = 'UPDATE_REQUISITION_SUCCESS';
export const UPDATE_REQUISITION_ERROR = 'UPDATE_REQUISITION_ERROR';
// ADD REQUISITION
export const REMOVE_REQUISITION = 'REMOVE_REQUISITION';
export const REMOVE_REQUISITION_SUCCESS = 'REMOVE_REQUISITION_SUCCESS';
export const REMOVE_REQUISITION_ERROR = 'REMOVE_REQUISITION_ERROR';
