// FETCH A COMPANY DETAILS
export const FETCH_COMPANY_DETAILS = 'FETCH_COMPANY_DETAILS';
export const FETCH_COMPANY_DETAILS_SUCCESS = 'FETCH_COMPANY_DETAILS_SUCCESS';
export const FETCH_COMPANY_DETAILS_ERROR = 'FETCH_COMPANY_DETAILS_ERROR';
