// FETCH CONTACT
export const FETCH_CONTACT_LIST = 'FETCH_CONTACT_LIST';
export const FETCH_CONTACT_LIST_SUCCESS = 'FETCH_CONTACT_LIST_SUCCESS';
export const FETCH_CONTACT_LIST_ERROR = 'FETCH_CONTACT_LIST_ERROR';

// REMOVE CONTACT
export const REMOVE_CONTACT = 'REMOVE_CONTACT';
export const REMOVE_CONTACT_SUCCESS = 'REMOVE_CONTACT_SUCCESS';
export const REMOVE_CONTACT_ERROR = 'REMOVE_CONTACT_ERROR';
