// FETCH LEAD tags
export const FETCH_LEAD_TAGS = 'FETCH_LEAD_TAGS';
export const FETCH_LEAD_TAGS_SUCCESS = 'FETCH_LEAD_TAGS_SUCCESS';
export const FETCH_LEAD_TAGS_ERROR = 'FETCH_LEAD_TAGS_ERROR';


// ADD LEAD tag
export const ADD_LEAD_TAG = 'ADD_LEAD_TAG';
export const ADD_LEAD_TAG_SUCCESS = 'ADD_LEAD_TAG_SUCCESS';
export const ADD_LEAD_TAG_ERROR = 'ADD_LEAD_TAG_ERROR';
