// FETCH JOB VACANCY
export const FETCH_JOB_VACANCY = 'FETCH_JOB_VACANCY';
export const FETCH_JOB_VACANCY_SUCCESS = 'FETCH_JOB_VACANCY_SUCCESS';
export const FETCH_JOB_VACANCY_ERROR = 'FETCH_JOB_VACANCY_ERROR';

// UPDATE COMPANY PROCESS
export const UPDATE_COMPANY_PROCESS = 'UPDATE_COMPANY_PROCESS';
export const UPDATE_COMPANY_PROCESS_SUCCESS = 'UPDATE_COMPANY_PROCESS_SUCCESS';
export const UPDATE_COMPANY_PROCESS_ERROR = 'UPDATE_COMPANY_PROCESS_ERROR';