// FETCH CALENDAR_EVENT
export const FETCH_CALENDAR_EVENT_LIST = 'FETCH_CALENDAR_EVENT_LIST';
export const FETCH_CALENDAR_EVENT_LIST_SUCCESS = 'FETCH_CALENDAR_EVENT_LIST_SUCCESS';
export const FETCH_CALENDAR_EVENT_LIST_ERROR = 'FETCH_CALENDAR_EVENT_LIST_ERROR';
// ADD CALENDAR_EVENT
export const ADD_CALENDAR_EVENT = 'ADD_CALENDAR_EVENT';
export const ADD_CALENDAR_EVENT_SUCCESS = 'ADD_CALENDAR_EVENT_SUCCESS';
export const ADD_CALENDAR_EVENT_ERROR = 'ADD_CALENDAR_EVENT_ERROR';
// UPDATE CALENDAR_EVENT
export const UPDATE_CALENDAR_EVENT = 'UPDATE_CALENDAR_EVENT';
export const UPDATE_CALENDAR_EVENT_SUCCESS = 'UPDATE_CALENDAR_EVENT_SUCCESS';
export const UPDATE_CALENDAR_EVENT_ERROR = 'UPDATE_CALENDAR_EVENT_ERROR';
// REMOVE CALENDAR_EVENT
export const REMOVE_CALENDAR_EVENT = 'REMOVE_CALENDAR_EVENT';
export const REMOVE_CALENDAR_EVENT_SUCCESS = 'REMOVE_CALENDAR_EVENT_SUCCESS';
export const REMOVE_CALENDAR_EVENT_ERROR = 'REMOVE_CALENDAR_EVENT_ERROR';
