// FETCH_USER_BY_ID_EMAIL
export const FETCH_USER_BY_ID_EMAIL = 'FETCH_USER_BY_ID_EMAIL';
export const FETCH_USER_BY_ID_EMAIL_SUCCESS = 'FETCH_USER_BY_ID_EMAIL_SUCCESS';
export const FETCH_USER_BY_ID_EMAIL_ERROR = 'FETCH_USER_BY_ID_EMAIL_ERROR';
// ADD_USER_BY_ID_EMAIL
export const ADD_USER_BY_ID_EMAIL = 'ADD_USER_BY_ID_EMAIL';
export const ADD_USER_BY_ID_EMAIL_SUCCESS = 'ADD_USER_BY_ID_EMAIL_SUCCESS';
export const ADD_USER_BY_ID_EMAIL_ERROR = 'ADD_USER_BY_ID_EMAIL_ERROR';
// UPDATE_USER_BY_ID_EMAIL
export const UPDATE_USER_BY_ID_EMAIL = 'UPDATE_USER_BY_ID_EMAIL';
export const UPDATE_USER_BY_ID_EMAIL_SUCCESS =
  'UPDATE_USER_BY_ID_EMAIL_SUCCESS';
export const UPDATE_USER_BY_ID_EMAIL_ERROR = 'UPDATE_USER_BY_ID_EMAIL_ERROR';
// REMOVE_USER_BY_ID_EMAIL
export const REMOVE_USER_BY_ID_EMAIL = 'REMOVE_USER_BY_ID_EMAIL';
export const REMOVE_USER_BY_ID_EMAIL_SUCCESS =
  'REMOVE_USER_BY_ID_EMAIL_SUCCESS';
export const REMOVE_USER_BY_ID_EMAIL_ERROR = 'REMOVE_USER_BY_ID_EMAIL_ERROR';
