// FETCH TASKS
export const FETCH_TASKS_LIST = 'FETCH_TASKS_LIST';
export const FETCH_TASKS_LIST_SUCCESS = 'FETCH_TASKS_LIST_SUCCESS';
export const FETCH_TASKS_LIST_ERROR = 'FETCH_TASKS_LIST_ERROR';
// ADD TASKS
export const ADD_TASK = 'ADD_TASK';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_ERROR = 'ADD_TASK_ERROR';
// UPDATE TASKS
export const UPDATE_TASKS = 'UPDATE_TASKS';
export const UPDATE_TASKS_SUCCESS = 'UPDATE_TASKS_SUCCESS';
export const UPDATE_TASKS_ERROR = 'UPDATE_TASKS_ERROR';
// REMOVE TASKS
export const REMOVE_TASKS = 'REMOVE_TASKS';
export const REMOVE_TASKS_SUCCESS = 'REMOVE_TASKS_SUCCESS';
export const REMOVE_TASKS_ERROR = 'REMOVE_TASKS_ERROR';
