// FETCH LOGGED_IN_USER
export const FETCH_LOGGED_IN_USER = 'FETCH_LOGGED_IN_USER';
export const FETCH_LOGGED_IN_USER_SUCCESS = 'FETCH_LOGGED_IN_USER_SUCCESS';
export const FETCH_LOGGED_IN_USER_ERROR = 'FETCH_LOGGED_IN_USER_ERROR';
// ADD LOGGED_IN_USER
export const ADD_LOGGED_IN_USER = 'ADD_LOGGED_IN_USER';
export const ADD_LOGGED_IN_USER_SUCCESS = 'ADD_LOGGED_IN_USER_SUCCESS';
export const ADD_LOGGED_IN_USER_ERROR = 'ADD_LOGGED_IN_USER_ERROR';
// UPDATE LOGGED_IN_USER
export const UPDATE_LOGGED_IN_USER = 'UPDATE_LOGGED_IN_USER';
export const UPDATE_LOGGED_IN_USER_SUCCESS = 'UPDATE_LOGGED_IN_USER_SUCCESS';
export const UPDATE_LOGGED_IN_USER_ERROR = 'UPDATE_LOGGED_IN_USER_ERROR';
// REMOVE LOGGED_IN_USER
export const REMOVE_LOGGED_IN_USER = 'REMOVE_LOGGED_IN_USER';
export const REMOVE_LOGGED_IN_USER_SUCCESS = 'REMOVE_LOGGED_IN_USER_SUCCESS';
export const REMOVE_LOGGED_IN_USER_ERROR = 'REMOVE_LOGGED_IN_USER_ERROR';
