// FETCH LOCATIONS
export const FETCH_LOCATION_LIST = 'FETCH_LOCATION_LIST';
export const FETCH_LOCATION_LIST_SUCCESS = 'FETCH_LOCATION_LIST_SUCCESS';
export const FETCH_LOCATION_LIST_ERROR = 'FETCH_LOCATION_LIST_ERROR';
