// FETCH TODO
export const FETCH_TODOS = 'FETCH_TODOS';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
export const FETCH_TODOS_ERROR = 'FETCH_TODOS_ERROR';

// FETCH TODO
export const ADD_TODO = 'ADD_TODO';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_ERROR = 'ADD_TODO_ERROR';

// UPDATE TODO IS_COMPLETED
export const UPDATE_TODO_ISCOMPLETED = 'UPDATE_TODO_ISCOMPLETED';
export const UPDATE_TODO_ISCOMPLETED_SUCCESS = 'UPDATE_TODO_ISCOMPLETED_SUCCESS';
export const UPDATE_TODO_ISCOMPLETED_ERROR = 'UPDATE_IS_COMPLETED_ERROR';
