// FETCH CONTACT
export const FETCH_DEAL_CONTACT_LIST = 'FETCH_DEAL_CONTACT_LIST';
export const FETCH_DEAL_CONTACT_LIST_SUCCESS = 'FETCH_DEAL_CONTACT_LIST_SUCCESS';
export const FETCH_DEAL_CONTACT_LIST_ERROR = 'FETCH_DEAL_CONTACT_LIST_ERROR';

// ADD CONTACT
export const ADD_DEAL_CONTACT = 'ADD_DEAL_CONTACT';
export const ADD_DEAL_CONTACT_SUCCESS = 'ADD_DEAL_CONTACT_SUCCESS';
export const ADD_DEAL_CONTACT_ERROR = 'ADD_DEAL_CONTACT_ERROR';

// UPDATE CONTACT
export const UPDATE_DEAL_CONTACT = 'UPDATE_DEAL_CONTACT';
export const UPDATE_DEAL_CONTACT_SUCCESS = 'UPDATE_DEAL_CONTACT_SUCCESS';
export const UPDATE_DEAL_CONTACT_ERROR = 'UPDATE_DEAL_CONTACT_ERROR';

// REMOVE CONTACT
export const REMOVE_DEAL_CONTACT = 'REMOVE_DEAL_CONTACT';
export const REMOVE_DEAL_CONTACT_SUCCESS = 'REMOVE_DEAL_CONTACT_SUCCESS';
export const REMOVE_DEAL_CONTACT_ERROR = 'REMOVE_DEAL_CONTACT_ERROR';
