// FETCH COMPANY
export const FETCH_LOGIN_AUTH = 'FETCH_LOGIN_AUTH';
export const FETCH_LOGIN_AUTH_SUCCESS = 'FETCH_LOGIN_AUTH_SUCCESS';
export const FETCH_LOGIN_AUTH_ERROR = 'FETCH_LOGIN_AUTH_ERROR';
// ADD COMPANY
export const ADD_LOGIN_AUTH = 'ADD_LOGIN_AUTH';
export const ADD_LOGIN_AUTH_SUCCESS = 'ADD_LOGIN_AUTH_SUCCESS';
export const ADD_LOGIN_AUTH_ERROR = 'ADD_LOGIN_AUTH_ERROR';
// UPDATE LOGIN_AUTH
export const UPDATE_LOGIN_AUTH = 'UPDATE_LOGIN_AUTH';
export const UPDATE_LOGIN_AUTH_SUCCESS = 'UPDATE_LOGIN_AUTH_SUCCESS';
export const UPDATE_LOGIN_AUTH_ERROR = 'UPDATE_LOGIN_AUTH_ERROR';
// REMOVE LOGIN_AUTH
export const REMOVE_LOGIN_AUTH = 'REMOVE_LOGIN_AUTH';
export const REMOVE_LOGIN_AUTH_SUCCESS = 'REMOVE_LOGIN_AUTH_SUCCESS';
export const REMOVE_LOGIN_AUTH_ERROR = 'REMOVE_LOGIN_AUTH_ERROR';
