// FETCH BRANCH LOCATION
export const FETCH_BRANCH_LOCATION_LIST = 'FETCH_BRANCH_LOCATION_LIST';
export const FETCH_BRANCH_LOCATION_LIST_SUCCESS = 'FETCH_BRANCH_LOCATION_LIST_SUCCESS';
export const FETCH_BRANCH_LOCATION_LIST_ERROR = 'FETCH_BRANCH_LOCATION_LIST_ERROR';
// ADD BRANCH LOCATION
export const ADD_BRANCH_LOCATION = 'ADD_BRANCH_LOCATION';
export const ADD_BRANCH_LOCATION_SUCCESS = 'ADD_BRANCH_LOCATION_SUCCESS';
export const ADD_BRANCH_LOCATION_ERROR = 'ADD_BRANCH_LOCATION_ERROR';
// UPDATE BRANCH LOCATION
export const UPDATE_BRANCH_LOCATION = 'UPDATE_BRANCH_LOCATION';
export const UPDATE_BRANCH_LOCATION_SUCCESS = 'UPDATE_BRANCH_LOCATION_SUCCESS';
export const UPDATE_BRANCH_LOCATION_ERROR = 'UPDATE_BRANCH_LOCATION_ERROR';
// ADD BRANCH LOCATION
export const REMOVE_BRANCH_LOCATION = 'REMOVE_BRANCH_LOCATION';
export const REMOVE_BRANCH_LOCATION_SUCCESS = 'REMOVE_BRANCH_LOCATION_SUCCESS';
export const REMOVE_BRANCH_LOCATION_ERROR = 'REMOVE_BRANCH_LOCATION_ERROR';


// FETCH HQ LOCATION
export const FETCH_HQ_LOCATION_LIST = 'FETCH_HQ_LOCATION_LIST';
export const FETCH_HQ_LOCATION_LIST_SUCCESS = 'FETCH_HQ_LOCATION_LIST_SUCCESS';
export const FETCH_HQ_LOCATION_LIST_ERROR = 'FETCH_HQ_LOCATION_LIST_ERROR';
// ADD HQ LOCATION
export const ADD_HQ_LOCATION = 'ADD_HQ_LOCATION';
export const ADD_HQ_LOCATION_SUCCESS = 'ADD_HQ_LOCATION_SUCCESS';
export const ADD_HQ_LOCATION_ERROR = 'ADD_HQ_LOCATION_ERROR';