// FETCH COMPANY
export const FETCH_REGISTER_AUTH = 'FETCH_REGISTER_AUTH';
export const FETCH_REGISTER_AUTH_SUCCESS = 'FETCH_REGISTER_AUTH_SUCCESS';
export const FETCH_REGISTER_AUTH_ERROR = 'FETCH_REGISTER_AUTH_ERROR';
// ADD COMPANY
export const ADD_REGISTER_AUTH = 'ADD_REGISTER_AUTH';
export const ADD_REGISTER_AUTH_SUCCESS = 'ADD_REGISTER_AUTH_SUCCESS';
export const ADD_REGISTER_AUTH_ERROR = 'ADD_REGISTER_AUTH_ERROR';
// UPDATE REGISTER_AUTH
export const UPDATE_REGISTER_AUTH = 'UPDATE_REGISTER_AUTH';
export const UPDATE_REGISTER_AUTH_SUCCESS = 'UPDATE_REGISTER_AUTH_SUCCESS';
export const UPDATE_REGISTER_AUTH_ERROR = 'UPDATE_REGISTER_AUTH_ERROR';
// REMOVE REGISTER_AUTH
export const REMOVE_REGISTER_AUTH = 'REMOVE_REGISTER_AUTH';
export const REMOVE_REGISTER_AUTH_SUCCESS = 'REMOVE_REGISTER_AUTH_SUCCESS';
export const REMOVE_REGISTER_AUTH_ERROR = 'REMOVE_REGISTER_AUTH_ERROR';
