// FETCH CANDIDATES BY SKILLS
export const FETCH_CANDIDATE_LIST_BY_SKILLS = 'FETCH_CANDIDATE_LIST_BY_SKILLS';
export const FETCH_CANDIDATE_LIST_BY_SKILLS_SUCCESS = 'FETCH_CANDIDATE_LIST_BY_SKILLS_SUCCESS';
export const FETCH_CANDIDATE_LIST_BY_SKILLS_ERROR = 'FETCH_CANDIDATE_LIST_BY_SKILLS_ERROR';
