// FETCH CONTACT
export const FETCH_COMPANY_CONTACT_LIST = 'FETCH_COMPANY_CONTACT_LIST';
export const FETCH_COMPANY_CONTACT_LIST_SUCCESS = 'FETCH_COMPANY_CONTACT_LIST_SUCCESS';
export const FETCH_COMPANY_CONTACT_LIST_ERROR = 'FETCH_COMPANY_CONTACT_LIST_ERROR';

// REMOVE CONTACT
export const REMOVE_COMPANY_CONTACT = 'REMOVE_COMPANY_CONTACT';
export const REMOVE_COMPANY_CONTACT_SUCCESS = 'REMOVE_COMPANY_CONTACT_SUCCESS';
export const REMOVE_COMPANY_CONTACT_ERROR = 'REMOVE_COMPANY_CONTACT_ERROR';
