// FETCH SKILLS
export const FETCH_SKILLS_LIST = 'FETCH_SKILL_LIST';
export const FETCH_SKILLS_LIST_SUCCESS = 'FETCH_SKILL_LIST_SUCCESS';
export const FETCH_SKILLS_LIST_ERROR = 'FETCH_SKILL_LIST_ERROR';
// ADD SKILL
export const ADD_SKILL = 'ADD_SKILL';
export const ADD_SKILL_SUCCESS = 'ADD_SKILL_SUCCESS';
export const ADD_SKILL_ERROR = 'ADD_SKILL_ERROR';
// UPDATE SKILL
export const UPDATE_SKILL = 'UPDATE_SKILL';
export const UPDATE_SKILL_SUCCESS = 'UPDATE_SKILL_SUCCESS';
export const UPDATE_SKILL_ERROR = 'UPDATE_SKILL_ERROR';
// ADD SKILL
export const REMOVE_SKILL = 'REMOVE_SKILL';
export const REMOVE_SKILL_SUCCESS = 'REMOVE_SKILL_SUCCESS';
export const REMOVE_SKILL_ERROR = 'REMOVE_SKILL_ERROR';
// 
// FETCH CANDIDATES BY SKILLS
export const FETCH_CANDIDATE_LIST_BY_SKILLS = 'FETCH_CANDIDATE_LIST_BY_SKILLS';
export const FETCH_CANDIDATE_LIST_BY_SKILLS_SUCCESS = 'FETCH_CANDIDATE_LIST_BY_SKILLS_SUCCESS';
export const FETCH_CANDIDATE_LIST_BY_SKILLS_ERROR = 'FETCH_CANDIDATE_LIST_BY_SKILLS_ERROR';
