// FETCH DEAL
export const FETCH_DEALS_LIST = 'FETCH_DEAL_LIST';
export const FETCH_DEALS_LIST_SUCCESS = 'FETCH_DEAL_LIST_SUCCESS';
export const FETCH_DEALS_LIST_ERROR = 'FETCH_DEAL_LIST_ERROR';
// ADD DEAL
export const ADD_DEAL = 'ADD_DEAL';
export const ADD_DEAL_SUCCESS = 'ADD_DEAL_SUCCESS';
export const ADD_DEAL_ERROR = 'ADD_DEAL_ERROR';
// UPDATE DEAL
export const UPDATE_DEAL = 'UPDATE_DEAL';
export const UPDATE_DEAL_SUCCESS = 'UPDATE_DEAL_SUCCESS';
export const UPDATE_DEAL_ERROR = 'UPDATE_DEAL_ERROR';
// REMOVE DEAL
export const REMOVE_DEAL = 'REMOVE_DEAL';
export const REMOVE_DEAL_SUCCESS = 'REMOVE_DEAL_SUCCESS';
export const REMOVE_DEAL_ERROR = 'REMOVE_DEAL_ERROR';

// CONVERT LEAD TO DEAL
export const CONVERT_LEAD_TO_DEAL = 'CONVERT_LEAD_TO_DEAL';
export const CONVERT_LEAD_TO_DEAL_SUCCESS = 'CONVERT_LEAD_TO_DEAL_SUCCESS';
export const CONVERT_LEAD_TO_DEAL_ERROR = 'CONVERT_LEAD_TO_DEAL_ERROR';

// FETCH DEAL DETAILS
export const FETCH_DEAL_DETAILS = 'FETCH_DEAL_DETAILS';
export const FETCH_DEAL_DETAILS_SUCCESS = 'FETCH_DEAL_DETAILS_SUCCESS';
export const FETCH_DEAL_DETAILS_ERROR = 'FETCH_DEAL_DETAILS_ERROR';

// UPDATE DEAL STAGE
export const UPDATE_DEAL_STAGE = 'UPDATE_DEAL_STAGE';
export const UPDATE_DEAL_STAGE_SUCCESS = 'UPDATE_DEAL_STAGE_SUCCESS';
export const UPDATE_DEAL_STAGE_ERROR = 'UPDATE_DEAL_STAGE_ERROR';

// FETCH DEAL COMPANY DETAILS
export const FETCH_DEAL_COMPANY_DETAILS = 'FETCH_DEAL_COMPANY_DETAILS';
export const FETCH_DEAL_COMPANY_DETAILS_SUCCESS = 'FETCH_DEAL_COMPANY_DETAILS_SUCCESS';
export const FETCH_DEAL_COMPANY_DETAILS_ERROR = 'FETCH_DEAL_COMPANY_DETAILS_ERROR';

// UPDATE DEAL COMPANY DETAILS
export const UPDATE_DEAL_COMPANY_DETAILS = 'UPDATE_DEAL_COMPANY_DETAILS';
export const UPDATE_DEAL_COMPANY_DETAILS_SUCCESS = 'UPDATE_DEAL_COMPANY_DETAILS_SUCCESS';
export const UPDATE_DEAL_COMPANY_DETAILS_ERROR = 'UPDATE_DEAL_COMPANY_DETAILS_ERROR';

// FETCH DEAL PRIMARY_CONTACT DETAILS
export const FETCH_DEAL_PRIMARY_CONTACT_DETAILS = 'FETCH_DEAL_PRIMARY_CONTACT_DETAILS';
export const FETCH_DEAL_PRIMARY_CONTACT_DETAILS_SUCCESS = 'FETCH_DEAL_PRIMARY_CONTACT_DETAILS_SUCCESS';
export const FETCH_DEAL_PRIMARY_CONTACT_DETAILS_ERROR = 'FETCH_DEAL_PRIMARY_CONTACT_DETAILS_ERROR';

// FETCH DEAL SECONDARY_CONTACT DETAILS
export const FETCH_DEAL_SECONDARY_CONTACT_LIST = 'FETCH_DEAL_SECONDARY_CONTACT_LIST';
export const FETCH_DEAL_SECONDARY_CONTACT_LIST_SUCCESS = 'FETCH_DEAL_SECONDARY_CONTACT_LIST_SUCCESS';
export const FETCH_DEAL_SECONDARY_CONTACT_LIST_ERROR = 'FETCH_DEAL_SECONDARY_CONTACT_LIST_ERROR';

// ADD DEAL SECONDARY_CONTACT DETAILS
export const ADD_DEAL_SECONDARY_CONTACT = 'ADD_DEAL_SECONDARY_CONTACT';
export const ADD_DEAL_SECONDARY_CONTACT_SUCCESS = 'ADD_DEAL_SECONDARY_CONTACT_SUCCESS';
export const ADD_DEAL_SECONDARY_CONTACT_ERROR = 'ADD_DEAL_SECONDARY_CONTACT_ERROR';


// UPDATE DEAL SECONDARY_CONTACT DETAILS
export const UPDATE_DEAL_SECONDARY_CONTACT = 'UPDATE_DEAL_SECONDARY_CONTACT';
export const UPDATE_DEAL_SECONDARY_CONTACT_SUCCESS = 'UPDATE_DEAL_SECONDARY_CONTACT_SUCCESS';
export const UPDATE_DEAL_SECONDARY_CONTACT_ERROR = 'UPDATE_DEAL_SECONDARY_CONTACT_ERROR';

// REMOVE DEAL SECONDARY_CONTACT DETAILS
export const REMOVE_DEAL_SECONDARY_CONTACT = 'REMOVE_DEAL_SECONDARY_CONTACT';
export const REMOVE_DEAL_SECONDARY_CONTACT_SUCCESS = 'REMOVE_DEAL_SECONDARY_CONTACT_SUCCESS';
export const REMOVE_DEAL_SECONDARY_CONTACT_ERROR = 'REMOVE_DEAL_SECONDARY_CONTACT_ERROR';

