// FETCH LEAD
export const FETCH_LEADS_LIST = 'FETCH_LEAD_LIST';
export const FETCH_LEADS_LIST_SUCCESS = 'FETCH_LEAD_LIST_SUCCESS';
export const FETCH_LEADS_LIST_ERROR = 'FETCH_LEAD_LIST_ERROR';
// ADD LEAD
export const ADD_LEAD = 'ADD_LEAD';
export const ADD_LEAD_SUCCESS = 'ADD_LEAD_SUCCESS';
export const ADD_LEAD_ERROR = 'ADD_LEAD_ERROR';
// UPDATE LEAD
export const UPDATE_LEAD = 'UPDATE_LEAD';
export const UPDATE_LEAD_SUCCESS = 'UPDATE_LEAD_SUCCESS';
export const UPDATE_LEAD_ERROR = 'UPDATE_LEAD_ERROR';
// REMOVE LEAD
export const REMOVE_LEAD = 'REMOVE_LEAD';
export const REMOVE_LEAD_SUCCESS = 'REMOVE_LEAD_SUCCESS';
export const REMOVE_LEAD_ERROR = 'REMOVE_LEAD_ERROR';
// BULK REMOVE LEAD
export const BULK_REMOVE_LEAD = 'BULK_REMOVE_LEAD';
export const BULK_REMOVE_LEAD_SUCCESS = 'BULK_REMOVE_LEAD_SUCCESS';
export const BULK_REMOVE_LEAD_ERROR = 'BULK_REMOVE_LEAD_ERROR';
// IMPORT LEAD FILE
export const IMPORT_LEAD_FILE = 'IMPORT_LEAD_FILE';
export const IMPORT_LEAD_FILE_SUCCESS = 'IMPORT_LEAD_FILE_SUCCESS';
export const IMPORT_LEAD_FILE_ERROR = 'IMPORT_LEAD_FILE_ERROR';
