// FETCH LOGGED_IN_USER_INFORMATION
export const FETCH_LOGGED_IN_USER_INFORMATION = 'FETCH_LOGGED_IN_USER_INFORMATION';
export const FETCH_LOGGED_IN_USER_INFORMATION_SUCCESS = 'FETCH_LOGGED_IN_USER_INFORMATION_SUCCESS';
export const FETCH_LOGGED_IN_USER_INFORMATION_ERROR = 'FETCH_LOGGED_IN_USER_INFORMATION_ERROR';
// ADD LOGGED_IN_USER_INFORMATION
export const ADD_LOGGED_IN_USER_INFORMATION = 'ADD_LOGGED_IN_USER_INFORMATION';
export const ADD_LOGGED_IN_USER_INFORMATION_SUCCESS = 'ADD_LOGGED_IN_USER_INFORMATION_SUCCESS';
export const ADD_LOGGED_IN_USER_INFORMATION_ERROR = 'ADD_LOGGED_IN_USER_INFORMATION_ERROR';
// UPDATE LOGGED_IN_USER_INFORMATION
export const UPDATE_LOGGED_IN_USER_INFORMATION = 'UPDATE_LOGGED_IN_USER_INFORMATION';
export const UPDATE_LOGGED_IN_USER_INFORMATION_SUCCESS = 'UPDATE_LOGGED_IN_USER_INFORMATION_SUCCESS';
export const UPDATE_LOGGED_IN_USER_INFORMATION_ERROR = 'UPDATE_LOGGED_IN_USER_INFORMATION_ERROR';
// REMOVE LOGGED_IN_USER_INFORMATION
// export const REMOVE_LOGGED_IN_USER_INFORMATION = 'REMOVE_LOGGED_IN_USER_INFORMATION';
// export const REMOVE_LOGGED_IN_USER_INFORMATION_SUCCESS = 'REMOVE_LOGGED_IN_USER_INFORMATION_SUCCESS';
// export const REMOVE_LOGGED_IN_USER_INFORMATION_ERROR = 'REMOVE_LOGGED_IN_USER_INFORMATION_ERROR';