// FETCH COMPANY
export const FETCH_COMPANY_LIST = 'FETCH_COMPANY_LIST';
export const FETCH_COMPANY_LIST_SUCCESS = 'FETCH_COMPANY_LIST_SUCCESS';
export const FETCH_COMPANY_LIST_ERROR = 'FETCH_COMPANY_LIST_ERROR';
// FETCH COMPANY FOR USER
export const FETCH_COMPANY_LIST_FORUSER = 'FETCH_COMPANY_LIST_FORUSER';
export const FETCH_COMPANY_LIST_FORUSER_SUCCESS = 'FETCH_COMPANY_LIST_FORUSER_SUCCESS';
export const FETCH_COMPANY_LIST_FORUSER_ERROR = 'FETCH_COMPANY_LIST_FORUSER_ERROR';
// ADD COMPANY
export const ADD_COMPANY = 'ADD_COMPANY';
export const ADD_COMPANY_SUCCESS = 'ADD_COMPANY_SUCCESS';
export const ADD_COMPANY_ERROR = 'ADD_COMPANY_ERROR';
// UPDATE COMPANY
export const UPDATE_COMPANY = 'UPDATE_COMPANY';
export const UPDATE_COMPANY_SUCCESS = 'UPDATE_COMPANY_SUCCESS';
export const UPDATE_COMPANY_ERROR = 'UPDATE_COMPANY_ERROR';
// REMOVE COMPANY FOR USER
export const REMOVE_COMPANY_FOR_USER = 'REMOVE_COMPANY_FOR_USER';
export const REMOVE_COMPANY_FOR_USER_SUCCESS = 'REMOVE_COMPANY_FOR_USER_SUCCESS';
export const REMOVE_COMPANY_FOR_USER_ERROR = 'REMOVE_COMPANY_FOR_USER_ERROR';
// REMOVE COMPANY BULK
export const Bulk_REMOVE_COMPANY_FOR_USER = 'Bulk_REMOVE_COMPANY_FOR_USER';
export const Bulk_REMOVE_COMPANY_FOR_USER_SUCCESS = 'Bulk_REMOVE_COMPANY_FOR_USER_SUCCESS';
export const Bulk_REMOVE_COMPANY_FOR_USER_ERROR = 'Bulk_REMOVE_COMPANY_FOR_USER_ERROR';
// FETCH A COMPANY DETAILS
export const FETCH_COMPANY_DETAILS = 'FETCH_COMPANY_DETAILS';
export const FETCH_COMPANY_DETAILS_SUCCESS = 'FETCH_COMPANY_DETAILS_SUCCESS';
export const FETCH_COMPANY_DETAILS_ERROR = 'FETCH_COMPANY_DETAILS_ERROR';
