// FETCH USER
export const FETCH_USER_LIST = 'FETCH_USER_LIST';
export const FETCH_USER_LIST_SUCCESS = 'FETCH_USER_LIST_SUCCESS';
export const FETCH_USER_LIST_ERROR = 'FETCH_USER_LIST_ERROR';
// // ADD USER
// export const ADD_USER = 'ADD_USER';
// export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
// export const ADD_USER_ERROR = 'ADD_USER_ERROR';
// // UPDATE USER
// export const UPDATE_USER = 'UPDATE_USER';
// export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
// export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
// // ADD USER
// export const REMOVE_USER = 'REMOVE_USER';
// export const REMOVE_USER_SUCCESS = 'REMOVE_USER_SUCCESS';
// export const REMOVE_USER_ERROR = 'REMOVE_USER_ERROR';
